export enum ORDER_DELIVERY_STATUS {
  ORDER_LOGISTIC_SHIPPING_CANCELLED = 'ORDER_LOGISTIC_SHIPPING_CANCELLED',
  ORDER_PENDING = 'ORDER_PENDING',
  ORDER_LOGISTICS_INFO_SENT = 'ORDER_LOGISTICS_INFO_SENT',
  ORDER_SCANNED = 'ORDER_SCANNED',
  ORDER_PREPARED = 'ORDER_PREPARED',
  ORDER_IN_TRANSIT = 'ORDER_IN_TRANSIT',
  ORDER_IN_TRANSIT_DELAYED = 'ORDER_IN_TRANSIT_DELAYED',
  ORDER_DELIVERY_POINT = 'ORDER_DELIVERY_POINT',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_DELIVERY_ERROR = 'ORDER_DELIVERY_ERROR',
  ADOPTED = 'Adopted',
  UNKNOWN = 'UNKNOWN',
}

export enum ORDER_PAYMENT_STATUS {
  ORDER_PAID = 'ORDER_PAID',
  ORDER_COLLECTED = 'ORDER_COLLECTED',
  TRANSFER_PAYMENT = 'TRANSFER_PAYMENT',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_DECLINED = 'ORDER_DECLINED',
  ORDER_REJECTED = 'ORDER_REJECTED',
  ORDER_PARTIALLY_REFUNDED = 'ORDER_PARTIALLY_REFUNDED',
  ORDER_REFUNDED = 'ORDER_REFUNDED',
  ORDER_PENDING = 'ORDER_PENDING',
}

export const VIEW_ORDER_PAYMENT_STATUS: Record<ORDER_PAYMENT_STATUS, string> = {
  [ORDER_PAYMENT_STATUS.ORDER_COLLECTED]: 'paid',
  [ORDER_PAYMENT_STATUS.ORDER_PAID]: 'paid',
  [ORDER_PAYMENT_STATUS.TRANSFER_PAYMENT]: 'paid',
  [ORDER_PAYMENT_STATUS.ORDER_REFUNDED]: 'refunded',
  [ORDER_PAYMENT_STATUS.ORDER_PARTIALLY_REFUNDED]: 'refunded',
  [ORDER_PAYMENT_STATUS.ORDER_PENDING]: 'pending',
  [ORDER_PAYMENT_STATUS.ORDER_CANCELLED]: 'cancel',
  [ORDER_PAYMENT_STATUS.ORDER_REJECTED]: 'rejected',
  [ORDER_PAYMENT_STATUS.ORDER_DECLINED]: 'rejected',
};

export enum ORDER_TICKET_STATUS {
  ORDER_TICKET_OPENED = 'ORDER_TICKET_OPENED',
  ORDER_TICKET_CLOSED = 'ORDER_TICKET_CLOSED',
  NONE = 'NONE',
}

export enum SUBSCRIPTION_STATUS {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
}

export enum GIFT_STATUS {
  PENDING = 'PENDING',
  CANCELLED = 'CANCELLED',
  ACCEPTED = 'ACCEPTED',
}

export enum ORDER_TYPE {
  ORDER_OVERHARVEST = 'OVERHARVEST',
  ORDER_MULTI_SHOT_ADOPTION = 'MULTI_SHOT_ADOPTION',
  ORDER_MULTI_SHOT_ADOPTION_RENEWAL = 'MULTI_SHOT_ADOPTION_RENEWAL',
  ONE_SHOT = 'ONE_SHOT',
  ONE_SHOT_RENEWAL = 'ONE_SHOT_RENEWAL',
  MULTI_SHOT_RENEWAL = 'MULTI_SHOT_RENEWAL',
  MULTI_SHOT_SINGLE_BOXES = 'MULTI_SHOT_SINGLE_BOXES',
  NEW_SHIPMENT_FARMER = 'NEW_SHIPMENT_FARMER',
  FREE_BOX = 'FREE_BOX',
  ECOMMERCE = 'ECOMMERCE',
}

export enum ORDER_STATUS {
  ADOPTED = 'adopted',
  CANCELLED = 'cancelled',
  CLOSED_INCIDENT = 'closed_incident',
  DECLINED = 'declined',
  DELIVERED = 'delivered',
  IN_PREPARATION = 'in_preparation',
  OPEN_INCIDENT = 'open_incident',
  PAID = 'paid',
  PLANNED = 'planned',
  POSSIBLE_DELAY = 'possible_delay',
  SENT = 'sent',
  REFUNDED = 'refunded',
  REJECTED = 'rejected',
}

export enum ORDER_SECTION_TYPE {
  INDIVIDUAL_ORDERS = 'individualOrders',
  GROUP_ORDER = 'groupOrders',
  SUBSCRIPTION_ORDERS = 'subscriptionOrders',
}

export enum ORDER_TYPES {
  INDIVIDUAL_ORDERS = 'INDIVIDUAL_ORDERS',
  GROUP_ORDERS = 'GROUP_ORDERS',
  RECURRENT_ORDERS = 'RECURRENT_ORDERS',
  ADOPTION_GIFT_ORDERS = 'ADOPTION_GIFT_ORDERS',
}

export const ORDER_STATUS_TRANSLATIONS: { [key in ORDER_STATUS]: string } = {
  [ORDER_STATUS.PLANNED]: 'global.planned.body',
  [ORDER_STATUS.IN_PREPARATION]: 'page.in-preparation.label',
  [ORDER_STATUS.SENT]: 'globa.sent.label',
  [ORDER_STATUS.POSSIBLE_DELAY]: 'global.possible-delay.drop',
  [ORDER_STATUS.DELIVERED]: 'global.delivered.label',
  [ORDER_STATUS.ADOPTED]: 'global.adopted.drop',
  [ORDER_STATUS.OPEN_INCIDENT]: 'global.open-incident.drop',
  [ORDER_STATUS.CLOSED_INCIDENT]: 'global.closed-incident.label',
  [ORDER_STATUS.CANCELLED]: 'global.cancelled.title',
  [ORDER_STATUS.REJECTED]: 'global.rejected.label',
  [ORDER_STATUS.DECLINED]: '-- DECLINED --',
  [ORDER_STATUS.PAID]: '-- PAID --',
  [ORDER_STATUS.REFUNDED]: '-- REFUNDED --',
};

export enum IMAGE_SIZE {
  SMALL = 'small',
  MEDIUM = 'medium',
}

export enum PURCHASE_ROLE {
  GUEST = 'GUEST',
  PROMOTER = 'PROMOTER',
  GIFTER = 'GIFTER',
  RECIPIENT = 'RECIPIENT',
  DEFAULT = 'DEFAULT',
}

export const SUBSCRIPTION_STATUS_TRANSLATIONS: { [key in SUBSCRIPTION_STATUS]: string } = {
  [SUBSCRIPTION_STATUS.PENDING]: 'page.pending.label',
  [SUBSCRIPTION_STATUS.COMPLETED]: 'page.completed.label',
  [SUBSCRIPTION_STATUS.IN_PROGRESS]: 'global.in-progress.label',
  [SUBSCRIPTION_STATUS.CANCELLED]: 'global.cancelled.title',
};
