export enum REMOTE_CONFIG {
  AGROUPMENTS_FARMERS_MARKET = 'agroupmentsFarmersMarket',
  APPLE_PAY_ENABLED = 'applePayEnabled',
  BANNERS = 'banners',
  BANNERS_FARMERS_MARKET = 'bannersFarmersMarket',
  CREDITS = 'credits',
  CS_ACTIVE_PARAMS = 'csActiveParams',
  FB_LOGIN = 'fbLogin',
  GIFT_ENABLED = 'giftEnabled',
  GOOGLE_LOGIN = 'googleLogin',
  GROUP_ORDER = 'groupOrder',
  GROUP_ORDER_MARKET = 'groupOrderMarket',
  HOTJAR = 'hotjar',
  KLARNA = 'klarna',
  LOG_ROCKET = 'logRocket',
  READY = 'ready',
  SHOW_OH_ADOPTION_PAGE = 'showOHAdoptionPage',
  SHOW_SMALL_BOX_FIRST = 'showSmallBoxFirst',
  SUBSCRIPTION = 'subscription',
  SUBSCRIPTION_MARKET = 'subscriptionMarket',
  TRADE_DOUBLER = 'tradeDoubler'
}
